Add `M-x xwwp`, update doc
canatella/xwwp pull request #8
Opened 2020-08-19 06:59 UTC by BlueFlo0d

I have this `xwwp` command in my `init.el` and find it useful so
I put it here to share.

Also updated some doc.

2020-08-19 07:22 UTC, canatella commented
Nice, thank you!

2020-08-19 07:33 UTC, canatella requested changes
Nice, thank you! Could you add some unit test for the xwwp--dwim-expand-url function ? Just add some tests in test/xwwp-test.el.

2020-08-19 07:33 UTC, canatella commented on xwwp.el
> +    (setq url (url-recreate-url parsed)))
Wouldn't it make sense to move this into its own function ? That way you could add a few unit test around this.

2020-08-19 07:41 UTC, canatella commented on xwwp.el
> +(defun xwwp--dwim-expand-url (url)
I don't use the `--` convention for private function anywhere. Could you use `xwwp-dwim-expand-url` here instead ?

2020-08-19 07:45 UTC, BlueFlo0d commented
sure I can change naming (probably tomorrow, late now).

I don't think we need our test from those -- they are basically copied directly from eww.
Compare to eww--dwim-expand url.
This patch is kind of trivial, but I do find it convinient.

2020-08-19 07:54 UTC, canatella commented
Is there a reason to not use `eww--dwim-expand-url` then ? Eww is distributed with emacs anyway.

2020-08-19 07:58 UTC, BlueFlo0d commented
The reason I copied it and changed a bit is I find I want to have different search prefix for eww and webkit -- for eww some query url with restrictimg options need to be used.

2020-08-19 08:01 UTC, BlueFlo0d commented
I think I can add some tests verifying the result of some input cases and even compare it to eww--* in case that eww ppl make their stuff better and we will know we may grab their new stuff.

It's not very likely though, those code are not updated since emacs 25 and it's using reading-string instead of better completing-read.

My next step will be to change it to completing-read so we can get a hint list like modern browsers, when using with some completion backend.

2020-08-19 08:18 UTC, canatella commented
Lexical binding is enabled so you should be able to use:

```emacs-lisp
(let ((eww-search-prefix xwwp-search-prefix))
  (eww--dwim-expand-url "foo bar baz"))
```

2020-08-19 08:20 UTC, BlueFlo0d commented
ah didn't notice this, yes.
Also formally in programming language this behavior is dynamic binding (if it's lexical binding then there should be no effect).
Will try this tomorrow.

2020-08-19 08:50 UTC, canatella commented
Ah yes indeed, it works because `eww-search-prefix` is a `defvar` that enforce dynamic bindings, thanks for pointing that out.

2020-08-19 17:59 UTC, BlueFlo0d commented
I use `eww--dwim-expand-url` now.
Any other change needed?

2020-08-20 04:35 UTC, BlueFlo0d commented
Not sure if it's proper to bring it up here:

I'm now trying to implement hint based on history -- and I need to get history first.
I didn't find any WebKit JS API for global browsing history.
Seems that the only way -- which I'm currently doing -- is to modify
to `xwwp-follow-link-trigger-action` and `xwwp-follow-link-action` to get
the link and save to history, and also advice `xwidget-webkit-browse-url`.
However in this way it doesn't capture the URL if user just click on the page,
or use some other mysterious way to navigate.

Any idea?

2020-08-20 09:15 UTC, canatella approved these changes

2020-08-20 09:21 UTC, canatella commented
> I use `eww--dwim-expand-url` now.
> Any other change needed?

They are two warnings that needs to be fixed for acceptance in melpa at https://github.com/canatella/xwwp/pull/8/checks?check_run_id=1004266114#step:8:12 

I guess you need to `(require 'eww)` and  `(require 'puny)`. You can run those check locally with `cask build`. Then it should be ok I guess.

2020-08-20 09:22 UTC, canatella commented
> Not sure if it's proper to bring it up here:
> 
> I'm now trying to implement hint based on history

What do you mean by hint ? The use case is not obvious to me :)

2020-08-20 19:07 UTC, kchanqvq commented
> > Not sure if it's proper to bring it up here:
> > I'm now trying to implement hint based on history
> 
> What do you mean by hint ? The use case is not obvious to me :)

When I type some words in the address bar of Chrome/Firefox/Safari etc they will give
completion candidates based on history URLs and titles.
It's kind of like helm in Emacs. But to do so I need to get browser history first.

Also I think browser history is useful in general, user might want to display them in a separate buffer etc.

2020-08-21 07:10 UTC, canatella commented
Alright, I see. There is probably a C api in webkit that would give you the history but then you'd have to expose it to the lisp environment. Otherwise I guess you are stuck with this "external" history.

2020-08-21 07:11 UTC, canatella commented
Don't forget to add the missing requires so I can merge this!

2020-08-21 18:21 UTC, kchanqvq commented
I made the changes, also fixed the `unwind-protect` form.

2020-08-23 01:39 UTC, kchanqvq commented
> Alright, I see. There is probably a C api in webkit that would give you the history but then you'd have to expose it to the lisp environment. Otherwise I guess you are stuck with this "external" history.

I figured out that I can advice `xwidget-webkit-callback`, then I can get full history.

Now that I'm implementing completion based on history I found that I could reuse `xwwp-follow-link-completion-***`. But currently the name suggest that they are local in package `xwwp-follow-link`.
Do you agree that I move them to `xwwp` namespace so other xwwp packages can reuse them?

Edit: actually, also less reasonable, it's easier to just `(require 'xwwp-follow-link)` in my `xwwp-history.el`.
So probably I'll just go for this.

BTW there's a commit of the ace-jump functionality in my branch. Here's a demo:
![ezgif-5-48b4a484563e](https://user-images.githubusercontent.com/6486990/90968888-ce584800-e4bf-11ea-8b94-053e6eecd863.gif)

2020-08-24 07:13 UTC, canatella commented
Could you first split the ace feature in its own branch, they are unrelated and I would like to merge this PR first. I really don't understand why the unwind protect was not working before. Could you explain me how to reproduce the C-g not working for you so that I can have a better understanding on why we would need two unwind-protect ?

2020-08-24 07:17 UTC, kchanqvq commented
Ah yes I splited the ace stuff to its own branch a while ago, currently the master branch should be clean.

There should be just one `unwind-protect`, I'll remove the duplicated one.

Originally in
```
(unwind-protect
        (condition-case nil
            (xwwp-follow-link-read xwwp-follow-link-completion-backend-instance
                                   "Link: " links
                                   (apply-partially #'xwwp-follow-link-trigger-action xwidget)
                                   (apply-partially #'xwwp-follow-link-update xwidget))
          (quit (xwwp-follow-link-cleanup xwidget)))
```
the unwind-protect form is doing nothing.
`(unwind-protect  BODYFORM UNWINDFORMS...)`, the `UNWINDFORMS` is just empty here.
So we should move the `(xwwp-follow-link-cleanup xwidget)` from the `condition-case` to the `unwind-protect`

2020-08-24 07:25 UTC, BlueFlo0d commented
also I think there's a bug in xwwp-follow-link-helm and I grabbed the fix from my branch.
CI is somehow failing... look like problem from elpa?

2020-08-24 12:40 UTC, canatella commented
Sorry to bother you, I really want to merge this but I think your `unwind-protect` changes introduces some problem in the browser it self, when I run `make test` on your branch now I get:

```
cask exec ert-runner --win
...
2020-08-24 14:28:14.313 Emacs[67744:341602] evaluateJavaScript error : A JavaScript exception occurred
2020-08-24 14:28:14.313 Emacs[67744:341602] error script=__xwidget_plus_follow_link_cleanup(null)
2020-08-24 14:28:16.311 Emacs[67744:341602] evaluateJavaScript error : A JavaScript exception occurred
2020-08-24 14:28:16.311 Emacs[67744:341602] error script=__xwidget_plus_follow_link_cleanup(null)
2020-08-24 14:28:18.814 Emacs[67744:341602] evaluateJavaScript error : A JavaScript exception occurred
2020-08-24 14:28:18.814 Emacs[67744:341602] error script=__xwidget_plus_follow_link_cleanup(null)
```
I would really like to help so if you could please explain me what is wrong with the current code in the master branch and how to reproduce the problem I could give it a shot. Thanks!

2020-08-24 13:03 UTC, BlueFlo0d commented
I reproduce the problem by evaluating those in `emacs -Q`
```
(require 'pacakge) (package-initialize)
(require 'helm) (helm-mode t)
(require 'xwwp) (setq xwwp-follow-link-completion-system 'helm)
```
then `M-x xwidget-webkit-browse-url https://google.com`, `M-x xwwp-follow-link`, then `C-g`.

For the helm problem, it currently focuses on the wrong link on some webpage with lots of links, e.g.
wikipedia page for emacs.

Also the `unwind-protect` fix itself should be sufficiently reasonable, and it's not related to those JS exceptions (I got those exceptions after reverting the `unwind-protect` code). Let me figure out what's wrong with those.

2020-08-24 13:35 UTC, BlueFlo0d commented
I just tried to use `cask emacs` instead, on your branch

There were no `C-g` cleanup problem, but the helm bug is still there.

So I think the helm fix is safe. 
`C-g` cleanup problem might depends on emacs/helm version.

2020-08-24 13:43 UTC, BlueFlo0d commented
I think the reason `C-g` didn't cleanup here is that `helm` doesn't signal a `quit` error
in my environment on `C-g`, instead, it just return nil without any error. So the cleanup
in `condition-case` is not called.

Using `unwind-protect` the cleanup will always be called, but potentially extraneously.
Those calls doesn't do harm anyway. The error lines are not Emacs errors --
they are printed to stderr by WebKitGTK, and seems harmless. What do you think?

2020-08-24 14:18 UTC, canatella commented
> I think the reason `C-g` didn't cleanup here is that `helm` doesn't signal a `quit` error
> in my environment on `C-g`, instead, it just return nil without any error. So the cleanup
> in `condition-case` is not called.

I think it might be better to make the helm backend `xwwp-follow-link-read` behave like the others by raising `quit` when it returns `nil`, does this code works with the original code:

```emacs-lisp
(cl-defmethod xwwp-follow-link-read ((backend xwwp-follow-link-completion-backend-helm) prompt collection action update-fn)
  (add-hook 'helm-after-initialize-hook (lambda ()
                                          (with-current-buffer "*helm-xwwp*"
                                            (add-hook 'helm-move-selection-after-hook update-fn nil t)))
            nil t)
  (or (helm :sources
        (helm-make-source "Xwidget Plus" 'helm-source-sync
                          :candidates collection
                          :action action
                          :filtered-candidate-transformer (lambda (candidates _)
                                                            (oset backend candidates candidates)
                                                            (funcall update-fn)
                                                            candidates))
        :prompt prompt
        :buffer "*helm-xwwp*") (signal 'quit nil)))
```
note the `or` and the `signal` call here.

> Those calls doesn't do harm anyway. The error lines are not Emacs errors --
> they are printed to stderr by WebKitGTK, and seems harmless. What do you think?

Yes they are printed by webkit but it is because we are somehow triggering an exception in the javascript code. It means we are doing something wrong. I'd like to avoid that as much as possible otherwise we might end up with lots of those errors and debugging javascript problems will become a hurdle. It is already difficult enough right now. If you can reproduce those error with the helm fix suggested above, I'll have a look at fixing them.

2020-08-24 20:39 UTC, BlueFlo0d commented
Yes looks that your hack solves everything! Thanks!

2020-08-25 07:12 UTC, canatella commented
Ok code looks nearly good, but you did not restore the `unwind-protect` that was there before, please add it back (it is there to catch possible unexpected errors). 

Then a few git history cleanup:

Could you rebase your branch to squash all the xwwp related commit in to one commit and rename that commit into something a bit more explicit like  
```
Add eww like command xwwp to search or browse

Provides a DWIM xwwp command that takes a string argument. It will display the corresponding web page if the argument is a URL. If not it will prefix the string with `xwwp-search-prefix` and visit that URL.
```

 (I try to follow https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines for writting commit messages),

Next, make sure the two helm fixes are split in their own commit, the one for the `C-g` problem with something like this for the commit message:

```
Fix xwwp-follow-link quit behaviour with Helm completion backend

When using helm and `C-g`, the Helm backend candidate function returns nil instead of propagating the `quit` signal which prevents the `xwwp-follow-link` cleanup to happen on `C-g` (the links stay highlighted) . This commit makes the Helm candidate function behave like the other ones by raising `quit` if it returns nil.
```
And another commit for the Helm link selection bug with a explicit commit message like this one.

And finally finally, could you add an `Authors` section to the readme, add myself and yourself there, something like:
```markdown
## Authors
- Damien Merenne <dam@cosinux.org>
- your name or pseudo and possibly email here.
```

2020-08-25 13:12 UTC, BlueFlo0d commented
The original `(unwind-protect ...)` did nothing, as I said, since the body form were empty. Try `(unwind-protect (signal t 1))`.

If you want to "eat" any lisp error, then we should do `(condition-case nil ... (quit ...) (t nil)`, but I'm not sure if that's a good idea. I would expect a debugger and backtrace when something potentially wrong happens in an emacs package.

2020-08-25 13:21 UTC, canatella commented
> The original `(unwind-protect ...)` did nothing, as I said, since the body form were empty. Try `(unwind-protect (signal t 1))`.
> 
> If you want to "eat" any lisp error, then we should do `(condition-case nil ... (quit ...) (t nil)`, but I'm not sure if that's a good idea. I would expect a debugger and backtrace when something potentially wrong happens in an emacs package.

Yeah, I must have added it for some reason though, but can't seem to remember

2020-08-25 13:25 UTC, canatella commented
Ok, just tested it without, looks ok here too., lets leave it like that. Just the git history cleanup and authors and its done.

2020-08-25 13:42 UTC, BlueFlo0d commented
Cleaned up git history.

CI somehow fails but `make test` passes when I run it locally.

2020-08-25 13:50 UTC, canatella commented
Damned, it is also ok here, but the CI is running against Emacs 26, I'm installing it rn to check if I can reproduce the problem.

2020-08-25 14:09 UTC, canatella commented
So I cannot test, I have no access to a Linux machine right now and emacs 26 on MacOS has no support for xwidget (I used the patch on 27 when developping). It seems that for some reason when running the test on CI some random page is loaded... Anyway lets merge this.

2020-08-25 14:09 UTC, merged

2020-08-27 06:24 UTC, BlueFlo0d commented
> Yes they are printed by webkit but it is because we are somehow triggering an exception in the javascript code. It means we are doing something wrong. I'd like to avoid that as much as possible otherwise we might end up with lots of those errors and debugging javascript problems will become a hurdle. It is already difficult enough right now. If you can reproduce those error with the helm fix suggested above, I'll have a look at fixing them.

BTW, did you know that on NS emacs you can right click > inspect element to get a full debug console? I didn't know this until I just read `nsxwidget.m` source.